[theme]

# primary interactive element accent
primaryColour = '#F2AE30'

# Main background
backgroundColor = '#8D92F2'

secondaryBackgroundColor = '#3D46F2'

textColor = '#0D0126'

font = "sans serif"